M48
; DRILL file {KiCad 9.0.7} date 2026-02-04T13:29:40+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-04T13:29:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.900
%
G90
G05
T1
X131.9Y-114.7
X142.9Y-114.7
T2
X134.9Y-119.7
X139.9Y-119.7
M30
