M48
; DRILL file {KiCad 9.0.7} date 2026-02-04T13:33:11+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-04T13:33:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0748
%
G90
G05
T1
X5.1929Y-4.5157
X5.626Y-4.5157
T2
X5.311Y-4.7126
X5.5079Y-4.7126
M30
