# TCL File Generated by Component Editor 24.1
# Tue Mar 24 19:08:42 CET 2026
# DO NOT MODIFY


# 
# register_limit_testing_module "register_limit_testing_module" v1.0
# Jacob Kvasnes 2026.03.24.19:08:42
# WASTED WAY TOO MUCH TIME ON THIS TESTER
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module register_limit_testing_module
# 
set_module_property DESCRIPTION "WASTED WAY TOO MUCH TIME ON THIS TESTER"
set_module_property NAME register_limit_testing_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Jacob Kvasnes"
set_module_property DISPLAY_NAME register_limit_testing_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL register_limit_testing_sbi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD_Display.vhd VHDL PATH LCD_Display.vhd
add_fileset_file ROM_7_SEG.vhd VHDL PATH ROM_7_SEG.vhd
add_fileset_file antiprell_key.vhd VHDL PATH antiprell_key.vhd
add_fileset_file bin3bcd.vhd VHDL PATH bin3bcd.vhd
add_fileset_file bin4bcd.vhd VHDL PATH bin4bcd.vhd
add_fileset_file binary_search.vhd VHDL PATH binary_search.vhd
add_fileset_file ram_for_data.vhd VHDL PATH ram_for_data.vhd
add_fileset_file register_find_one_variable.vhd VHDL PATH register_find_one_variable.vhd
add_fileset_file register_limit_testing.vhd VHDL PATH register_limit_testing.vhd
add_fileset_file register_test_handler.vhd VHDL PATH register_test_handler.vhd
add_fileset_file register_limit_testing_sbi.vhd VHDL PATH register_limit_testing_sbi.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 writedata writedata Input 16
add_interface_port avalon_slave_0 readdata readdata Output 16
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit hex0_port hex0_sig Output 7
add_interface_port conduit hex1_port hex1_sig Output 7
add_interface_port conduit hex2_port hex2_sig Output 7
add_interface_port conduit hex3_port hex3_sig Output 7
add_interface_port conduit hex4_port hex4_sig Output 7
add_interface_port conduit hex5_port hex5_sig Output 7
add_interface_port conduit hex6_port hex6_sig Output 7
add_interface_port conduit hex7_port hex7_sig Output 7
add_interface_port conduit lcd_data_port lcd_data_sig Bidir 8
add_interface_port conduit lcd_en_port lcd_en_sig Output 1
add_interface_port conduit lcd_rs_port lcd_rs_sig Output 1
add_interface_port conduit lcd_rw_port lcd_rw_sig Output 1
add_interface_port conduit gpio_port gpio_sig Bidir 36
add_interface_port conduit key_port key_sig Input 3
add_interface_port conduit ledg_port ledg_sig Output 8
add_interface_port conduit sw_port sw_sig Input 18


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1

